
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv
from generator import *

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():

    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    
    S, n, V, F, sigma, G, where = get_input()
    class mf_struct:
        def __init__(self):
            self.S = [] # projected values
            self.n = 0 # number of grouping variables
            self.V = [] # group by attributes
            self.F = [] # list of aggregates
            self.sigma = [] # grouping variables predicates 
            self.G = None # having clause
    mf_struct = mf_struct() 
    mf_struct.S = S
    mf_struct.n = n
    mf_struct.V = V
    mf_struct.F = F
    mf_struct.sigma = sigma
    mf_struct.G = G
    H = H_table(mf_struct, where)
    
    
    return tabulate.tabulate(H,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    